# Configurations for Netlify
# https://www.netlify.com/docs/netlify-toml-reference/

[build]

publish = "dist/"
command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
	Cache-Control = "public, max-age=0, no-cache, no-store, must-revalidate"
